### PR TITLE
[For 2.6.x] Fix the size of rotated images in the gallery application

### LINKED ISSUE #2537: Rotated images have incorrect sizes in the gallery application
## Bug description & symptom

When rotating an image in the gallery, it does not occupy all the available space.

## Expected

After rotate an image on the gallery, it must be resized to take upall the available space.

## How to reproduce

1. Open gallery
2. Visualize image which can be rotated
3. Rotate it

## Screenshots

rotate

## Impacted components

*Optional - list components which will be impacted.*

- *frontend*

### PR DESCRIPTION
**Pull request by raphj**
Related to #2537.

## Checkpoints

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

- [x] Tested by quality team

### CODE REVIEW

File: frontend_app_gallery/src/component/MainPreview.jsx [hunk 1]
```diff
@@ -2,32 +2,88 @@ import React from 'react'
...
-      height: img.height,
-      width: img.width,
       imageLoaded: true
     })
   }
 
-  render () {
-    const { props, state } = this
+  fixImageSize () {
+    if (this.props.rotationAngle % 180) {
```
Comment (Skylsmoi) [inline frontend_app_gallery/src/component/MainPreview.jsx]: from my understanding, since this function is always called on component update and if props.rotationAngle is different than 0 or 180, the computing in the requestAnimatinoFrame will happen on every "compoenentDidUpdate" until rotationAngle change.

Since componentDidUpdate can be fired a lot of time (eg. especially when it has async requests related to it) I'm a bit afraid of the javascript computation amount than can be required.
Also, ref in React are attached to the DOM, not the virtual DOM. So it cannot fully use React high performance related to the virtual DOM.

Is it possible to call ifxImageSize on componendDidUpdate only when rotationAngle change ?

If not, just do some performance check on the rotation and update process. I might be wrong.

Comment (Skylsmoi) [reply frontend_app_gallery/src/component/MainPreview.jsx]: Pm me about this if I'm not clear enough

File: frontend_app_gallery/src/component/MainPreview.jsx [hunk 2]
```diff
@@ -2,32 +2,88 @@ import React from 'react'
...
     this.setState({
-      height: img.height,
-      width: img.width,
       imageLoaded: true
     })
   }
 
-  render () {
-    const { props, state } = this
+  fixImageSize () {
```
Comment (Skylsmoi) [inline frontend_app_gallery/src/component/MainPreview.jsx]: I would like a more precise name for this function

I'm not entirely sure about everything it does but I would call it something like fixImageRatioForRotation

File: frontend_app_gallery/src/component/MainPreview.jsx (hunk 1 above)
Comment (metzgegu) [reply frontend_app_gallery/src/component/MainPreview.jsx:36]: Yes, It is possible to call `fixImageSize` only when the rotationAngle has changed, the size has to be changed only in this case

File: frontend_app_gallery/src/component/MainPreview.jsx (hunk 2 above)
Comment (metzgegu) [reply frontend_app_gallery/src/component/MainPreview.jsx]: Yes this function name isn't precise enough,

I think `fixImageRatioForRotation` is a good name but I would prefer `compute` to `fix` because we don't really fix something that is broken.

File: frontend_app_gallery/test/component/MainPreview.spec.js [hunk 3]
```diff
@@ -13,7 +13,12 @@ describe('<MainPreview />', () => {
     handleClickShowImageRaw
   }
 
-  const wrapper = shallow(<MainPreview {...props} t={tradKey => tradKey} />)
+  // INFO - GM - 2020/04/15 - Mock some window functions used by MainPreview
+  window.requestAnimationFrame = (cb) => { cb() }
+  window.getComputedStyle = () => { return {} }
```
Comment (Skylsmoi) [inline frontend_app_gallery/test/component/MainPreview.spec.js:18]: I think it would fit best in test/setup.js
see  window.matchMedia for example

Also, since requestAnimationFrame is supposed not to answer immediately, wrap the cb() in a setTimeout of, I don't know, 10ms should be fine. It'll reflect better what is happening in browser

File: frontend_app_gallery/test/setup.js [hunk 4]
```diff
@@ -32,4 +32,7 @@ window.matchMedia = window.matchMedia || function() {
     removeListener: function() {}
   }
 }
+// INFO - GM - 2020/04/15 - Mock some window functions used by MainPreview
+window.requestAnimationFrame = (cb) => setTimeout(cb, 10)
+window.getComputedStyle = () => ({})
```
Comment (Skylsmoi) [inline frontend_app_gallery/test/setup.js:37]: as I said, use the matchMedia example to avoid overriding the property if it isn't required

**Comment by gbonaspetti** [comment]
Tested and verified on branch.

**Comment by raphj** [comment]
Thanks @Skylsmoi and @metzgegu, and sorry, I did not see this discussion.

**Comment by Skylsmoi** [comment]
> Thanks @Skylsmoi and @metzgegu, and sorry, I did not see this discussion.

don't worry, you where on a different task, it was up to us to complete the pr
