### PR TITLE
Various bux fixes 2.4

### LINKED ISSUE #2158: Hidden lower part of collabora's iframe
## Bug description & symptom

The lower part of collabora iframe is not visible.

## Expected

The lower part of collabora iframe should be visible.

### PR DESCRIPTION
**Pull request by basilelegal**
Fixes #2158 , #2160, #2157

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

### CODE REVIEW

File: frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx [hunk 1]
```diff
@@ -32,12 +32,19 @@ class CollaborativeEditionFrame extends React.Component {
...
+      loggedUser: props.data.loggedUser
     }
   }
 
   async componentDidMount () {
-    console.log('%c<CollaboraFrame> did mount', `color: ${this.props.data.config.hexcolor}`)
+    const { props } = this
+    console.log('%c<CollaboraFrame> did mount', `color: ${this.props.data.config.hexcolor}`, props)
+    if (!this.checkUserPermissions()) {
+      this.sendGlobalFlashMessage(props.t("You don't have the permission to edit this file"))
```
Comment (lebouquetin) [inline frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx]: You should write "You are not allowed to edit this file"

Comment (basilelegal) [reply frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx]: done
