### PR TITLE
Fix/2275 making inside menu clickable, adding a tooltip and some responsive css fix

### LINKED ISSUE #2275: Make the menu inside the apps fully clickable and add a tooltip
## Bug description & symptom

Make the menu inside the apps fully clickable to close the right part and add a tooltip about it.

### PR DESCRIPTION
**Pull request by gbonaspetti**
#2275

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

### CODE REVIEW

**Comment by basilelegal** [comment]
waiting for merge conflicts and cypress tests to be fixed

File: frontend_lib/src/component/ShareDownload/ShareDownloadManagement.jsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ class ShareDownloadManagement extends React.Component {
     const shareLinkList = props.shareLinkList ? props.shareLinkList : []
     
     return (
-      <div className='shareDownload'>
+      <div>
```
Comment (Skylsmoi) [inline frontend_lib/src/component/ShareDownload/ShareDownloadManagement.jsx]: use a Fragment instead of a div without any html attributes.
See: https://reactjs.org/docs/fragments.html

you can use the short syntax

File: frontend_lib/src/component/ShareDownload/ShareDownload.styl [hunk 2]
```diff
@@ -71,6 +72,10 @@
   &__newBtn
     margin-right 30px
 
+// MEDIAQUERIES
+
 @media (min-width: min-xs) and (max-width: max-lg)
   .shareDownload
     margin-top 0px
+    height calc(100% - 65px)
```
Comment (Skylsmoi) [inline frontend_lib/src/component/ShareDownload/ShareDownload.styl]: add comment to explain magic number (the 65)

File: frontend_lib/src/component/Timeline/Timeline.styl [hunk 3]
```diff
@@ -3,8 +3,7 @@
 .timeline
   display flex
   flex-direction column
-  border-radius 10px
-  width 100%
+  width calc(100% - 65px)
```
Comment (Skylsmoi) [inline frontend_lib/src/component/Timeline/Timeline.styl]: add comment to explain magic number (the 65)

File: frontend_lib/src/component/Timeline/Timeline.styl [hunk 4]
```diff
@@ -71,11 +70,12 @@ columnTimeline()
     display flex
     flex-direction column
     margin 0
+    height calc(100% - 65px)
```
Comment (Skylsmoi) [inline frontend_lib/src/component/Timeline/Timeline.styl]: add comment to explain magic number (the 65)

File: frontend_app_file/src/component/FileProperties.styl [hunk 5]
```diff
@@ -36,3 +36,10 @@
         &__btndesc
           margin-top 10px
           margin-left auto
+
+// MEDIAQUERIES
+
+@media (min-width: min-xs) and (max-width: max-lg)
+  .fileProperties
+    height calc(100% - 65px)
```
Comment (Skylsmoi) [inline frontend_app_file/src/component/FileProperties.styl]: add comment to explain magic number (the 65)

File: frontend_app_file/src/component/FileProperties.styl [hunk 6]
```diff
@@ -1,7 +1,7 @@
 @import "../../node_modules/tracim_frontend_lib/src/css/Variable.styl"
 
 .fileProperties
-  width 100%
+  width calc(100% - 65px)
```
Comment (Skylsmoi) [inline frontend_app_file/src/component/FileProperties.styl]: add comment to explain magic number (the 65)
